dist: xenial
language: python
sudo: False
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -U Markdown pelican codecov pytest pytest-cov
- pip install .
script: pytest --cov=./
after_success: codecov
